### ISSUE TITLE
Sync Now - Integrity error on MySQL

### ISSUE THREAD

**Issue by nrmay** [mytardis/mytardis-app-mydata#8]
I’m getting the following error when pressing 'Sync Now’: 
- Error appears in .MyData_debug_log.txt
- Data files upload and verify fine via the web portal.
- No filters or patterns have been set.

> folders.pyc - 229 - ShowMessageDialog - MainThread - WARNING - Refusing to show message dialog for message "{ "error_message": "(1062, \"Duplicate entry 'b929f735-e2d3-11e6-954a-3c07542f560e' for key ‘uuid’\”)", 
> ...
>File \"/opt/mytardis/develop-cas/lib/python2.7/site-packages/django/db/backends/utils.py\", line 64, in execute\n    return self.cursor.execute(sql, params)\n\n  
>File \"/opt/mytardis/develop-cas/lib/python2.7/site-packages/django/db/backends/mysql/base.py\", line 124, in execute\n    return self.cursor.execute(query, args)\n\n  
>File \"/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py\", line 174, in execute\n    self.errorhandler(self, exc, value)\n\n  
>File \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\", line 36, in defaulterrorhandler\n    raise errorclass, errorvalue\n\nIntegrityError: (1062, \"Duplicate entry 'b929f735-e2d3-11e6-954a-3c07542f560e' for key 'uuid'\")\n

Any ideas?

**Comment by wettenhj** [comment]
Each MyData instance (known as an "Uploader") generates a universally unique ID (uuid) for itself.  The uuid can be found in the MyData.cfg file (e.g. ~/Library/Application\ Support/MyData/MyData.cfg on Mac OS X).  If MyData doesn't find any existing Uploader records for its uuid on the MyTardis server, it will create one with POST, but if it finds an existing Uploader record, it will try to update it with PUT.  See: http://django-tastypie.readthedocs.io/en/latest/interacting.html#updating-an-existing-resource-put and https://github.com/mytardis/mydata/blob/develop/mydata/models/uploader.py#L443

Maybe the PUT isn't being interpreted correctly by your MyTardis API, and it's trying to create a new (duplicate) Uploader record instead of updating the existing one.

Maybe add some logging to tardis/apps/mydata/api.py in the UploaderAppResource class, and check whether the object creation method (obj_create) is being called or the update method (obj_update).

**Comment by nrmay** [comment]
Ok. I'll give it a try.

Nicholas May

Software Developer (Research Data)
eResearch Office
Research & Innovation Portfolio
RMIT University
T: 03 992 54069
E: nicholas.may@rmit.edu.au

On Mon, Jan 30, 2017 at 12:23 PM, James Wettenhall <notifications@github.com

**Comment by nrmay** [comment]
Not been fixed here.
